// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academic.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveEnrollments = `-- name: CountActiveEnrollments :one
SELECT COUNT(*)::int AS count
FROM enrollments
WHERE tenant_id = $1 AND course_id = $2 AND semester = $3 AND status = 'active'
`

type CountActiveEnrollmentsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	CourseID uuid.UUID `json:"course_id"`
	Semester string    `json:"semester"`
}

func (q *Queries) CountActiveEnrollments(ctx context.Context, arg CountActiveEnrollmentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveEnrollments, arg.TenantID, arg.CourseID, arg.Semester)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (tenant_id, code, name, credits, department_id, seat_cap)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, code, name, credits, department_id, seat_cap, created_at
`

type CreateCourseParams struct {
	TenantID     uuid.UUID      `json:"tenant_id"`
	Code         string         `json:"code"`
	Name         string         `json:"name"`
	Credits      pgtype.Numeric `json:"credits"`
	DepartmentID pgtype.UUID    `json:"department_id"`
	SeatCap      int32          `json:"seat_cap"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Credits,
		arg.DepartmentID,
		arg.SeatCap,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.DepartmentID,
		&i.SeatCap,
		&i.CreatedAt,
	)
	return i, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (tenant_id, code, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, code, name, created_at
`

type CreateDepartmentParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Code     string    `json:"code"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.TenantID, arg.Code, arg.Name)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (tenant_id, student_id, course_id, semester, status, idempotency_key)
VALUES ($1, $2, $3, $4, 'active', $5)
RETURNING id, tenant_id, student_id, course_id, semester, status, idempotency_key, created_at
`

type CreateEnrollmentParams struct {
	TenantID       uuid.UUID   `json:"tenant_id"`
	StudentID      uuid.UUID   `json:"student_id"`
	CourseID       uuid.UUID   `json:"course_id"`
	Semester       string      `json:"semester"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.TenantID,
		arg.StudentID,
		arg.CourseID,
		arg.Semester,
		arg.IdempotencyKey,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.CourseID,
		&i.Semester,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const createRegistrationWindow = `-- name: CreateRegistrationWindow :one
INSERT INTO registration_windows (tenant_id, name, semester, opens_at, closes_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, semester, opens_at, closes_at, created_at
`

type CreateRegistrationWindowParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Semester string    `json:"semester"`
	OpensAt  time.Time `json:"opens_at"`
	ClosesAt time.Time `json:"closes_at"`
}

func (q *Queries) CreateRegistrationWindow(ctx context.Context, arg CreateRegistrationWindowParams) (RegistrationWindow, error) {
	row := q.db.QueryRow(ctx, createRegistrationWindow,
		arg.TenantID,
		arg.Name,
		arg.Semester,
		arg.OpensAt,
		arg.ClosesAt,
	)
	var i RegistrationWindow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Semester,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedAt,
	)
	return i, err
}

const dropEnrollment = `-- name: DropEnrollment :one
UPDATE enrollments SET status = 'dropped'
WHERE tenant_id = $1 AND student_id = $2 AND course_id = $3 AND semester = $4 AND status = 'active'
RETURNING id, tenant_id, student_id, course_id, semester, status, idempotency_key, created_at
`

type DropEnrollmentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
	CourseID  uuid.UUID `json:"course_id"`
	Semester  string    `json:"semester"`
}

func (q *Queries) DropEnrollment(ctx context.Context, arg DropEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, dropEnrollment,
		arg.TenantID,
		arg.StudentID,
		arg.CourseID,
		arg.Semester,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.CourseID,
		&i.Semester,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, tenant_id, code, name, credits, department_id, seat_cap, created_at FROM courses WHERE tenant_id = $1 AND id = $2
`

type GetCourseByIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetCourseByID(ctx context.Context, arg GetCourseByIDParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, arg.TenantID, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.DepartmentID,
		&i.SeatCap,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentByIdempotency = `-- name: GetEnrollmentByIdempotency :one
SELECT id, tenant_id, student_id, course_id, semester, status, idempotency_key, created_at FROM enrollments WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetEnrollmentByIdempotencyParams struct {
	TenantID       uuid.UUID   `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetEnrollmentByIdempotency(ctx context.Context, arg GetEnrollmentByIdempotencyParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.CourseID,
		&i.Semester,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenRegistrationWindow = `-- name: GetOpenRegistrationWindow :one
SELECT id, tenant_id, name, semester, opens_at, closes_at, created_at FROM registration_windows
WHERE tenant_id = $1 AND semester = $2 AND opens_at <= now() AND closes_at >= now()
ORDER BY opens_at DESC
LIMIT 1
`

type GetOpenRegistrationWindowParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Semester string    `json:"semester"`
}

func (q *Queries) GetOpenRegistrationWindow(ctx context.Context, arg GetOpenRegistrationWindowParams) (RegistrationWindow, error) {
	row := q.db.QueryRow(ctx, getOpenRegistrationWindow, arg.TenantID, arg.Semester)
	var i RegistrationWindow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Semester,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCourseRoster = `-- name: ListCourseRoster :many
SELECT e.id, e.tenant_id, e.student_id, e.course_id, e.semester, e.status, e.idempotency_key, e.created_at, s.roll_number, s.program, s.batch_year, u.full_name, u.email
FROM enrollments e
JOIN students s ON s.id = e.student_id
JOIN users u ON u.id = s.user_id
WHERE e.tenant_id = $1 AND e.course_id = $2 AND e.semester = $3 AND e.status = 'active'
ORDER BY s.roll_number
`

type ListCourseRosterParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	CourseID uuid.UUID `json:"course_id"`
	Semester string    `json:"semester"`
}

type ListCourseRosterRow struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	StudentID      uuid.UUID   `json:"student_id"`
	CourseID       uuid.UUID   `json:"course_id"`
	Semester       string      `json:"semester"`
	Status         string      `json:"status"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	CreatedAt      time.Time   `json:"created_at"`
	RollNumber     string      `json:"roll_number"`
	Program        string      `json:"program"`
	BatchYear      int32       `json:"batch_year"`
	FullName       string      `json:"full_name"`
	Email          string      `json:"email"`
}

func (q *Queries) ListCourseRoster(ctx context.Context, arg ListCourseRosterParams) ([]ListCourseRosterRow, error) {
	rows, err := q.db.Query(ctx, listCourseRoster, arg.TenantID, arg.CourseID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseRosterRow{}
	for rows.Next() {
		var i ListCourseRosterRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.CourseID,
			&i.Semester,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.RollNumber,
			&i.Program,
			&i.BatchYear,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, tenant_id, code, name, credits, department_id, seat_cap, created_at FROM courses WHERE tenant_id = $1 ORDER BY code
`

func (q *Queries) ListCourses(ctx context.Context, tenantID uuid.UUID) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Credits,
			&i.DepartmentID,
			&i.SeatCap,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, tenant_id, code, name, created_at FROM departments WHERE tenant_id = $1 ORDER BY code
`

func (q *Queries) ListDepartments(ctx context.Context, tenantID uuid.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentEnrollments = `-- name: ListStudentEnrollments :many
SELECT id, tenant_id, student_id, course_id, semester, status, idempotency_key, created_at FROM enrollments
WHERE tenant_id = $1 AND student_id = $2 AND status = 'active'
ORDER BY created_at
`

type ListStudentEnrollmentsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) ListStudentEnrollments(ctx context.Context, arg ListStudentEnrollmentsParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listStudentEnrollments, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Enrollment{}
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.CourseID,
			&i.Semester,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentEnrollmentsWithCourse = `-- name: ListStudentEnrollmentsWithCourse :many
SELECT e.id, e.course_id, e.semester, e.status, e.created_at,
       c.code AS course_code, c.name AS course_name, c.credits, c.seat_cap
FROM enrollments e
JOIN courses c ON c.id = e.course_id
WHERE e.tenant_id = $1 AND e.student_id = $2 AND e.status = 'active'
ORDER BY c.code
`

type ListStudentEnrollmentsWithCourseParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

type ListStudentEnrollmentsWithCourseRow struct {
	ID         uuid.UUID      `json:"id"`
	CourseID   uuid.UUID      `json:"course_id"`
	Semester   string         `json:"semester"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	CourseCode string         `json:"course_code"`
	CourseName string         `json:"course_name"`
	Credits    pgtype.Numeric `json:"credits"`
	SeatCap    int32          `json:"seat_cap"`
}

func (q *Queries) ListStudentEnrollmentsWithCourse(ctx context.Context, arg ListStudentEnrollmentsWithCourseParams) ([]ListStudentEnrollmentsWithCourseRow, error) {
	rows, err := q.db.Query(ctx, listStudentEnrollmentsWithCourse, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentEnrollmentsWithCourseRow{}
	for rows.Next() {
		var i ListStudentEnrollmentsWithCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Semester,
			&i.Status,
			&i.CreatedAt,
			&i.CourseCode,
			&i.CourseName,
			&i.Credits,
			&i.SeatCap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCourseForUpdate = `-- name: LockCourseForUpdate :one
SELECT id, tenant_id, code, name, credits, department_id, seat_cap, created_at FROM courses WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type LockCourseForUpdateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) LockCourseForUpdate(ctx context.Context, arg LockCourseForUpdateParams) (Course, error) {
	row := q.db.QueryRow(ctx, lockCourseForUpdate, arg.TenantID, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.DepartmentID,
		&i.SeatCap,
		&i.CreatedAt,
	)
	return i, err
}
