// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attendance.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attendanceStatsForStudentCourse = `-- name: AttendanceStatsForStudentCourse :one
SELECT
  COUNT(*)::int AS total,
  COUNT(*) FILTER (WHERE status IN ('present', 'late'))::int AS present
FROM attendance
WHERE tenant_id = $1 AND student_id = $2 AND course_id = $3
`

type AttendanceStatsForStudentCourseParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

type AttendanceStatsForStudentCourseRow struct {
	Total   int32 `json:"total"`
	Present int32 `json:"present"`
}

func (q *Queries) AttendanceStatsForStudentCourse(ctx context.Context, arg AttendanceStatsForStudentCourseParams) (AttendanceStatsForStudentCourseRow, error) {
	row := q.db.QueryRow(ctx, attendanceStatsForStudentCourse, arg.TenantID, arg.StudentID, arg.CourseID)
	var i AttendanceStatsForStudentCourseRow
	err := row.Scan(&i.Total, &i.Present)
	return i, err
}

const listAttendanceForStudent = `-- name: ListAttendanceForStudent :many
SELECT id, tenant_id, student_id, course_id, session_date, status, marked_by, created_at FROM attendance
WHERE tenant_id = $1 AND student_id = $2
ORDER BY session_date DESC
`

type ListAttendanceForStudentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) ListAttendanceForStudent(ctx context.Context, arg ListAttendanceForStudentParams) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listAttendanceForStudent, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attendance{}
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.CourseID,
			&i.SessionDate,
			&i.Status,
			&i.MarkedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendance = `-- name: UpsertAttendance :one
INSERT INTO attendance (tenant_id, student_id, course_id, session_date, status, marked_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, student_id, course_id, session_date)
DO UPDATE SET status = EXCLUDED.status, marked_by = EXCLUDED.marked_by
RETURNING id, tenant_id, student_id, course_id, session_date, status, marked_by, created_at
`

type UpsertAttendanceParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	StudentID   uuid.UUID   `json:"student_id"`
	CourseID    uuid.UUID   `json:"course_id"`
	SessionDate pgtype.Date `json:"session_date"`
	Status      string      `json:"status"`
	MarkedBy    pgtype.UUID `json:"marked_by"`
}

func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, upsertAttendance,
		arg.TenantID,
		arg.StudentID,
		arg.CourseID,
		arg.SessionDate,
		arg.Status,
		arg.MarkedBy,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.CourseID,
		&i.SessionDate,
		&i.Status,
		&i.MarkedBy,
		&i.CreatedAt,
	)
	return i, err
}
