// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fees.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFeeHead = `-- name: CreateFeeHead :one
INSERT INTO fee_heads (tenant_id, name, amount, due_date, late_fee_amount, applicable_programs)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, amount, due_date, late_fee_amount, applicable_programs, created_at
`

type CreateFeeHeadParams struct {
	TenantID           uuid.UUID      `json:"tenant_id"`
	Name               string         `json:"name"`
	Amount             pgtype.Numeric `json:"amount"`
	DueDate            pgtype.Date    `json:"due_date"`
	LateFeeAmount      pgtype.Numeric `json:"late_fee_amount"`
	ApplicablePrograms []string       `json:"applicable_programs"`
}

func (q *Queries) CreateFeeHead(ctx context.Context, arg CreateFeeHeadParams) (FeeHead, error) {
	row := q.db.QueryRow(ctx, createFeeHead,
		arg.TenantID,
		arg.Name,
		arg.Amount,
		arg.DueDate,
		arg.LateFeeAmount,
		arg.ApplicablePrograms,
	)
	var i FeeHead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Amount,
		&i.DueDate,
		&i.LateFeeAmount,
		&i.ApplicablePrograms,
		&i.CreatedAt,
	)
	return i, err
}

const createFeePayment = `-- name: CreateFeePayment :one
INSERT INTO fee_payments (tenant_id, student_id, fee_head_id, amount, status, idempotency_key, gateway_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, student_id, fee_head_id, amount, status, idempotency_key, gateway_ref, paid_at, created_at
`

type CreateFeePaymentParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	StudentID      uuid.UUID      `json:"student_id"`
	FeeHeadID      uuid.UUID      `json:"fee_head_id"`
	Amount         pgtype.Numeric `json:"amount"`
	Status         string         `json:"status"`
	IdempotencyKey string         `json:"idempotency_key"`
	GatewayRef     pgtype.Text    `json:"gateway_ref"`
}

func (q *Queries) CreateFeePayment(ctx context.Context, arg CreateFeePaymentParams) (FeePayment, error) {
	row := q.db.QueryRow(ctx, createFeePayment,
		arg.TenantID,
		arg.StudentID,
		arg.FeeHeadID,
		arg.Amount,
		arg.Status,
		arg.IdempotencyKey,
		arg.GatewayRef,
	)
	var i FeePayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.FeeHeadID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.GatewayRef,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFeeHead = `-- name: GetFeeHead :one
SELECT id, tenant_id, name, amount, due_date, late_fee_amount, applicable_programs, created_at FROM fee_heads WHERE tenant_id = $1 AND id = $2
`

type GetFeeHeadParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetFeeHead(ctx context.Context, arg GetFeeHeadParams) (FeeHead, error) {
	row := q.db.QueryRow(ctx, getFeeHead, arg.TenantID, arg.ID)
	var i FeeHead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Amount,
		&i.DueDate,
		&i.LateFeeAmount,
		&i.ApplicablePrograms,
		&i.CreatedAt,
	)
	return i, err
}

const getFeePaymentByID = `-- name: GetFeePaymentByID :one
SELECT id, tenant_id, student_id, fee_head_id, amount, status, idempotency_key, gateway_ref, paid_at, created_at FROM fee_payments WHERE tenant_id = $1 AND id = $2
`

type GetFeePaymentByIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetFeePaymentByID(ctx context.Context, arg GetFeePaymentByIDParams) (FeePayment, error) {
	row := q.db.QueryRow(ctx, getFeePaymentByID, arg.TenantID, arg.ID)
	var i FeePayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.FeeHeadID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.GatewayRef,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFeePaymentByIdempotency = `-- name: GetFeePaymentByIdempotency :one
SELECT id, tenant_id, student_id, fee_head_id, amount, status, idempotency_key, gateway_ref, paid_at, created_at FROM fee_payments WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetFeePaymentByIdempotencyParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetFeePaymentByIdempotency(ctx context.Context, arg GetFeePaymentByIdempotencyParams) (FeePayment, error) {
	row := q.db.QueryRow(ctx, getFeePaymentByIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i FeePayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.FeeHeadID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.GatewayRef,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFeeHeads = `-- name: ListFeeHeads :many
SELECT id, tenant_id, name, amount, due_date, late_fee_amount, applicable_programs, created_at FROM fee_heads WHERE tenant_id = $1 ORDER BY due_date NULLS LAST, name
`

func (q *Queries) ListFeeHeads(ctx context.Context, tenantID uuid.UUID) ([]FeeHead, error) {
	rows, err := q.db.Query(ctx, listFeeHeads, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeHead{}
	for rows.Next() {
		var i FeeHead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Amount,
			&i.DueDate,
			&i.LateFeeAmount,
			&i.ApplicablePrograms,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentPayments = `-- name: ListStudentPayments :many
SELECT id, tenant_id, student_id, fee_head_id, amount, status, idempotency_key, gateway_ref, paid_at, created_at FROM fee_payments WHERE tenant_id = $1 AND student_id = $2 ORDER BY created_at DESC
`

type ListStudentPaymentsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) ListStudentPayments(ctx context.Context, arg ListStudentPaymentsParams) ([]FeePayment, error) {
	rows, err := q.db.Query(ctx, listStudentPayments, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeePayment{}
	for rows.Next() {
		var i FeePayment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.FeeHeadID,
			&i.Amount,
			&i.Status,
			&i.IdempotencyKey,
			&i.GatewayRef,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpaidFeeHeadsForStudent = `-- name: ListUnpaidFeeHeadsForStudent :many
SELECT fh.id, fh.tenant_id, fh.name, fh.amount, fh.due_date, fh.late_fee_amount, fh.applicable_programs, fh.created_at
FROM fee_heads fh
WHERE fh.tenant_id = $1
  AND (fh.applicable_programs = '{}' OR $2 = ANY(fh.applicable_programs))
  AND NOT EXISTS (
    SELECT 1 FROM fee_payments fp
    WHERE fp.tenant_id = fh.tenant_id
      AND fp.fee_head_id = fh.id
      AND fp.student_id = $3
      AND fp.status = 'paid'
  )
ORDER BY fh.due_date NULLS LAST
`

type ListUnpaidFeeHeadsForStudentParams struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	ApplicablePrograms []string  `json:"applicable_programs"`
	StudentID          uuid.UUID `json:"student_id"`
}

func (q *Queries) ListUnpaidFeeHeadsForStudent(ctx context.Context, arg ListUnpaidFeeHeadsForStudentParams) ([]FeeHead, error) {
	rows, err := q.db.Query(ctx, listUnpaidFeeHeadsForStudent, arg.TenantID, arg.ApplicablePrograms, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeHead{}
	for rows.Next() {
		var i FeeHead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Amount,
			&i.DueDate,
			&i.LateFeeAmount,
			&i.ApplicablePrograms,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeePaymentPaid = `-- name: MarkFeePaymentPaid :one
UPDATE fee_payments
SET status = 'paid', paid_at = now(), gateway_ref = COALESCE($3, gateway_ref)
WHERE tenant_id = $1 AND id = $2 AND status = 'pending'
RETURNING id, tenant_id, student_id, fee_head_id, amount, status, idempotency_key, gateway_ref, paid_at, created_at
`

type MarkFeePaymentPaidParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	ID         uuid.UUID   `json:"id"`
	GatewayRef pgtype.Text `json:"gateway_ref"`
}

func (q *Queries) MarkFeePaymentPaid(ctx context.Context, arg MarkFeePaymentPaidParams) (FeePayment, error) {
	row := q.db.QueryRow(ctx, markFeePaymentPaid, arg.TenantID, arg.ID, arg.GatewayRef)
	var i FeePayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.FeeHeadID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.GatewayRef,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}
