// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: misc.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStudentsForTenant = `-- name: CountStudentsForTenant :one
SELECT COUNT(*)::int AS count FROM students WHERE tenant_id = $1
`

func (q *Queries) CountStudentsForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countStudentsForTenant, tenantID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (tenant_id, author_id, title, body, audience_scope, audience_filter)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, author_id, title, body, audience_scope, audience_filter, created_at
`

type CreateAnnouncementParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	AuthorID       uuid.UUID       `json:"author_id"`
	Title          string          `json:"title"`
	Body           string          `json:"body"`
	AudienceScope  string          `json:"audience_scope"`
	AudienceFilter json.RawMessage `json:"audience_filter"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.TenantID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.AudienceScope,
		arg.AudienceFilter,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.AudienceScope,
		&i.AudienceFilter,
		&i.CreatedAt,
	)
	return i, err
}

const createBulkJob = `-- name: CreateBulkJob :one

INSERT INTO bulk_jobs (tenant_id, job_type, status, created_by)
VALUES ($1, $2, 'pending', $3)
RETURNING id, tenant_id, job_type, status, total_rows, success_rows, error_report, created_by, created_at, completed_at
`

type CreateBulkJobParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	JobType   string      `json:"job_type"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

// The outbox relay spans every tenant, so it cannot run inside a tenant's RLS
// scope. It goes through the SECURITY DEFINER functions added in migration
// 000002; sqlc cannot type set-returning functions, so those calls live in
// internal/db/outbox.go instead of here.
func (q *Queries) CreateBulkJob(ctx context.Context, arg CreateBulkJobParams) (BulkJob, error) {
	row := q.db.QueryRow(ctx, createBulkJob, arg.TenantID, arg.JobType, arg.CreatedBy)
	var i BulkJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobType,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.ErrorReport,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (tenant_id, student_id, type, status)
VALUES ($1, $2, $3, 'requested')
RETURNING id, tenant_id, student_id, type, status, storage_ref, generated_at, created_at
`

type CreateDocumentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
	Type      string    `json:"type"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.TenantID, arg.StudentID, arg.Type)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.Type,
		&i.Status,
		&i.StorageRef,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTimetableSlot = `-- name: CreateTimetableSlot :one
INSERT INTO timetable_slots (tenant_id, course_id, semester, day_of_week, start_time, end_time, room)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, course_id, semester, day_of_week, start_time, end_time, room, created_at
`

type CreateTimetableSlotParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	CourseID  uuid.UUID   `json:"course_id"`
	Semester  string      `json:"semester"`
	DayOfWeek int32       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Room      pgtype.Text `json:"room"`
}

func (q *Queries) CreateTimetableSlot(ctx context.Context, arg CreateTimetableSlotParams) (TimetableSlot, error) {
	row := q.db.QueryRow(ctx, createTimetableSlot,
		arg.TenantID,
		arg.CourseID,
		arg.Semester,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Room,
	)
	var i TimetableSlot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Semester,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Room,
		&i.CreatedAt,
	)
	return i, err
}

const getBulkJob = `-- name: GetBulkJob :one
SELECT id, tenant_id, job_type, status, total_rows, success_rows, error_report, created_by, created_at, completed_at FROM bulk_jobs WHERE tenant_id = $1 AND id = $2
`

type GetBulkJobParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetBulkJob(ctx context.Context, arg GetBulkJobParams) (BulkJob, error) {
	row := q.db.QueryRow(ctx, getBulkJob, arg.TenantID, arg.ID)
	var i BulkJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobType,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.ErrorReport,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, tenant_id, student_id, type, status, storage_ref, generated_at, created_at FROM documents WHERE tenant_id = $1 AND id = $2
`

type GetDocumentParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.TenantID, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.Type,
		&i.Status,
		&i.StorageRef,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (tenant_id, actor_id, action, entity, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	TenantID uuid.UUID       `json:"tenant_id"`
	ActorID  pgtype.UUID     `json:"actor_id"`
	Action   string          `json:"action"`
	Entity   string          `json:"entity"`
	EntityID pgtype.UUID     `json:"entity_id"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (tenant_id, topic, payload)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, topic, payload, published_at, created_at, attempts, last_error, failed_at
`

type InsertOutboxParams struct {
	TenantID uuid.UUID       `json:"tenant_id"`
	Topic    string          `json:"topic"`
	Payload  json.RawMessage `json:"payload"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutbox, arg.TenantID, arg.Topic, arg.Payload)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Topic,
		&i.Payload,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.Attempts,
		&i.LastError,
		&i.FailedAt,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, tenant_id, author_id, title, body, audience_scope, audience_filter, created_at FROM announcements
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAnnouncementsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.AudienceScope,
			&i.AudienceFilter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, actor_id, action, entity, entity_id, metadata, created_at FROM audit_log WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListAuditLogsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBulkJobs = `-- name: ListBulkJobs :many
SELECT id, tenant_id, job_type, status, total_rows, success_rows, error_report, created_by, created_at, completed_at FROM bulk_jobs WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListBulkJobsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListBulkJobs(ctx context.Context, arg ListBulkJobsParams) ([]BulkJob, error) {
	rows, err := q.db.Query(ctx, listBulkJobs, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BulkJob{}
	for rows.Next() {
		var i BulkJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobType,
			&i.Status,
			&i.TotalRows,
			&i.SuccessRows,
			&i.ErrorReport,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsForTenant = `-- name: ListPushSubscriptionsForTenant :many
SELECT id, tenant_id, user_id, endpoint, p256dh, auth, created_at FROM push_subscriptions WHERE tenant_id = $1
`

func (q *Queries) ListPushSubscriptionsForTenant(ctx context.Context, tenantID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentDocuments = `-- name: ListStudentDocuments :many
SELECT id, tenant_id, student_id, type, status, storage_ref, generated_at, created_at FROM documents WHERE tenant_id = $1 AND student_id = $2 ORDER BY created_at DESC
`

type ListStudentDocumentsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) ListStudentDocuments(ctx context.Context, arg ListStudentDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listStudentDocuments, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.Type,
			&i.Status,
			&i.StorageRef,
			&i.GeneratedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimetableForSemester = `-- name: ListTimetableForSemester :many
SELECT t.id, t.tenant_id, t.course_id, t.semester, t.day_of_week, t.start_time, t.end_time, t.room, t.created_at, c.code AS course_code, c.name AS course_name
FROM timetable_slots t
JOIN courses c ON c.id = t.course_id
WHERE t.tenant_id = $1 AND t.semester = $2
ORDER BY t.day_of_week, t.start_time
`

type ListTimetableForSemesterParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Semester string    `json:"semester"`
}

type ListTimetableForSemesterRow struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	CourseID   uuid.UUID   `json:"course_id"`
	Semester   string      `json:"semester"`
	DayOfWeek  int32       `json:"day_of_week"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
	Room       pgtype.Text `json:"room"`
	CreatedAt  time.Time   `json:"created_at"`
	CourseCode string      `json:"course_code"`
	CourseName string      `json:"course_name"`
}

func (q *Queries) ListTimetableForSemester(ctx context.Context, arg ListTimetableForSemesterParams) ([]ListTimetableForSemesterRow, error) {
	rows, err := q.db.Query(ctx, listTimetableForSemester, arg.TenantID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimetableForSemesterRow{}
	for rows.Next() {
		var i ListTimetableForSemesterRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.Semester,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Room,
			&i.CreatedAt,
			&i.CourseCode,
			&i.CourseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBulkJob = `-- name: UpdateBulkJob :one
UPDATE bulk_jobs
SET status = $2, total_rows = $3, success_rows = $4, error_report = $5, completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN now() ELSE completed_at END
WHERE tenant_id = $6 AND id = $1
RETURNING id, tenant_id, job_type, status, total_rows, success_rows, error_report, created_by, created_at, completed_at
`

type UpdateBulkJobParams struct {
	ID          uuid.UUID       `json:"id"`
	Status      string          `json:"status"`
	TotalRows   int32           `json:"total_rows"`
	SuccessRows int32           `json:"success_rows"`
	ErrorReport json.RawMessage `json:"error_report"`
	TenantID    uuid.UUID       `json:"tenant_id"`
}

func (q *Queries) UpdateBulkJob(ctx context.Context, arg UpdateBulkJobParams) (BulkJob, error) {
	row := q.db.QueryRow(ctx, updateBulkJob,
		arg.ID,
		arg.Status,
		arg.TotalRows,
		arg.SuccessRows,
		arg.ErrorReport,
		arg.TenantID,
	)
	var i BulkJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobType,
		&i.Status,
		&i.TotalRows,
		&i.SuccessRows,
		&i.ErrorReport,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status = $2, storage_ref = COALESCE($4, storage_ref),
    generated_at = CASE WHEN $2 = 'ready' THEN now() ELSE generated_at END
WHERE tenant_id = $3 AND id = $1
RETURNING id, tenant_id, student_id, type, status, storage_ref, generated_at, created_at
`

type UpdateDocumentStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	StorageRef pgtype.Text `json:"storage_ref"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus,
		arg.ID,
		arg.Status,
		arg.TenantID,
		arg.StorageRef,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.Type,
		&i.Status,
		&i.StorageRef,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
INSERT INTO push_subscriptions (tenant_id, user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, endpoint)
DO UPDATE SET p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth, user_id = EXCLUDED.user_id
RETURNING id, tenant_id, user_id, endpoint, p256dh, auth, created_at
`

type UpsertPushSubscriptionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
	P256dh   string    `json:"p256dh"`
	Auth     string    `json:"auth"`
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.TenantID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTenantUsage = `-- name: UpsertTenantUsage :exec
INSERT INTO tenant_usage_daily (tenant_id, day, request_count, error_count, student_count)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, day)
DO UPDATE SET
  request_count = tenant_usage_daily.request_count + EXCLUDED.request_count,
  error_count = tenant_usage_daily.error_count + EXCLUDED.error_count,
  student_count = EXCLUDED.student_count
`

type UpsertTenantUsageParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	Day          pgtype.Date `json:"day"`
	RequestCount int64       `json:"request_count"`
	ErrorCount   int64       `json:"error_count"`
	StudentCount int32       `json:"student_count"`
}

func (q *Queries) UpsertTenantUsage(ctx context.Context, arg UpsertTenantUsageParams) error {
	_, err := q.db.Exec(ctx, upsertTenantUsage,
		arg.TenantID,
		arg.Day,
		arg.RequestCount,
		arg.ErrorCount,
		arg.StudentCount,
	)
	return err
}
