// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	AuthorID       uuid.UUID       `json:"author_id"`
	Title          string          `json:"title"`
	Body           string          `json:"body"`
	AudienceScope  string          `json:"audience_scope"`
	AudienceFilter json.RawMessage `json:"audience_filter"`
	CreatedAt      time.Time       `json:"created_at"`
}

type Attendance struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	StudentID   uuid.UUID   `json:"student_id"`
	CourseID    uuid.UUID   `json:"course_id"`
	SessionDate pgtype.Date `json:"session_date"`
	Status      string      `json:"status"`
	MarkedBy    pgtype.UUID `json:"marked_by"`
	CreatedAt   time.Time   `json:"created_at"`
}

type AuditLog struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	ActorID   pgtype.UUID     `json:"actor_id"`
	Action    string          `json:"action"`
	Entity    string          `json:"entity"`
	EntityID  pgtype.UUID     `json:"entity_id"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

type BulkJob struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	JobType     string             `json:"job_type"`
	Status      string             `json:"status"`
	TotalRows   int32              `json:"total_rows"`
	SuccessRows int32              `json:"success_rows"`
	ErrorReport json.RawMessage    `json:"error_report"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Course struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	Code         string         `json:"code"`
	Name         string         `json:"name"`
	Credits      pgtype.Numeric `json:"credits"`
	DepartmentID pgtype.UUID    `json:"department_id"`
	SeatCap      int32          `json:"seat_cap"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Department struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Document struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	StudentID   uuid.UUID          `json:"student_id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	StorageRef  pgtype.Text        `json:"storage_ref"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Enrollment struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	StudentID      uuid.UUID   `json:"student_id"`
	CourseID       uuid.UUID   `json:"course_id"`
	Semester       string      `json:"semester"`
	Status         string      `json:"status"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Faculty struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	UserID       uuid.UUID   `json:"user_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	EmployeeID   pgtype.Text `json:"employee_id"`
	CreatedAt    time.Time   `json:"created_at"`
}

type FeeHead struct {
	ID                 uuid.UUID      `json:"id"`
	TenantID           uuid.UUID      `json:"tenant_id"`
	Name               string         `json:"name"`
	Amount             pgtype.Numeric `json:"amount"`
	DueDate            pgtype.Date    `json:"due_date"`
	LateFeeAmount      pgtype.Numeric `json:"late_fee_amount"`
	ApplicablePrograms []string       `json:"applicable_programs"`
	CreatedAt          time.Time      `json:"created_at"`
}

type FeePayment struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	StudentID      uuid.UUID          `json:"student_id"`
	FeeHeadID      uuid.UUID          `json:"fee_head_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	GatewayRef     pgtype.Text        `json:"gateway_ref"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type LoginEvent struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Ip        pgtype.Text `json:"ip"`
	UserAgent pgtype.Text `json:"user_agent"`
	CreatedAt time.Time   `json:"created_at"`
}

type Outbox struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Topic       string             `json:"topic"`
	Payload     json.RawMessage    `json:"payload"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   time.Time          `json:"created_at"`
	Attempts    int32              `json:"attempts"`
	LastError   pgtype.Text        `json:"last_error"`
	FailedAt    pgtype.Timestamptz `json:"failed_at"`
}

type PushSubscription struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	Endpoint  string    `json:"endpoint"`
	P256dh    string    `json:"p256dh"`
	Auth      string    `json:"auth"`
	CreatedAt time.Time `json:"created_at"`
}

type RegistrationWindow struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	Semester  string    `json:"semester"`
	OpensAt   time.Time `json:"opens_at"`
	ClosesAt  time.Time `json:"closes_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Result struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	StudentID        uuid.UUID          `json:"student_id"`
	CourseID         uuid.UUID          `json:"course_id"`
	Semester         string             `json:"semester"`
	Grade            string             `json:"grade"`
	GradePoints      pgtype.Numeric     `json:"grade_points"`
	Marks            pgtype.Numeric     `json:"marks"`
	SubmissionStatus string             `json:"submission_status"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	EnteredBy        pgtype.UUID        `json:"entered_by"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type Student struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	UserID       uuid.UUID   `json:"user_id"`
	RollNumber   string      `json:"roll_number"`
	Program      string      `json:"program"`
	BatchYear    int32       `json:"batch_year"`
	DepartmentID pgtype.UUID `json:"department_id"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Tenant struct {
	ID           uuid.UUID   `json:"id"`
	Slug         string      `json:"slug"`
	Name         string      `json:"name"`
	CustomDomain pgtype.Text `json:"custom_domain"`
	Status       string      `json:"status"`
	PlanTier     string      `json:"plan_tier"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type TenantConfig struct {
	TenantID               uuid.UUID       `json:"tenant_id"`
	GradingSystem          string          `json:"grading_system"`
	AcademicCalendarType   string          `json:"academic_calendar_type"`
	Branding               json.RawMessage `json:"branding"`
	FeeHeads               json.RawMessage `json:"fee_heads"`
	AttendanceThresholdPct pgtype.Numeric  `json:"attendance_threshold_pct"`
	GradingScale           json.RawMessage `json:"grading_scale"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              time.Time       `json:"updated_at"`
}

type TenantUsageDaily struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	Day          pgtype.Date `json:"day"`
	RequestCount int64       `json:"request_count"`
	ErrorCount   int64       `json:"error_count"`
	StudentCount int32       `json:"student_count"`
}

type TimetableSlot struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	CourseID  uuid.UUID   `json:"course_id"`
	Semester  string      `json:"semester"`
	DayOfWeek int32       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Room      pgtype.Text `json:"room"`
	CreatedAt time.Time   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	FullName     string    `json:"full_name"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
