// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFaculty = `-- name: CreateFaculty :one
INSERT INTO faculty (tenant_id, user_id, department_id, employee_id)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, department_id, employee_id, created_at
`

type CreateFacultyParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	UserID       uuid.UUID   `json:"user_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	EmployeeID   pgtype.Text `json:"employee_id"`
}

func (q *Queries) CreateFaculty(ctx context.Context, arg CreateFacultyParams) (Faculty, error) {
	row := q.db.QueryRow(ctx, createFaculty,
		arg.TenantID,
		arg.UserID,
		arg.DepartmentID,
		arg.EmployeeID,
	)
	var i Faculty
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.CreatedAt,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (tenant_id, user_id, roll_number, program, batch_year, department_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, user_id, roll_number, program, batch_year, department_id, created_at
`

type CreateStudentParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	UserID       uuid.UUID   `json:"user_id"`
	RollNumber   string      `json:"roll_number"`
	Program      string      `json:"program"`
	BatchYear    int32       `json:"batch_year"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.TenantID,
		arg.UserID,
		arg.RollNumber,
		arg.Program,
		arg.BatchYear,
		arg.DepartmentID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RollNumber,
		&i.Program,
		&i.BatchYear,
		&i.DepartmentID,
		&i.CreatedAt,
	)
	return i, err
}

const getFacultyByUserID = `-- name: GetFacultyByUserID :one
SELECT id, tenant_id, user_id, department_id, employee_id, created_at FROM faculty WHERE tenant_id = $1 AND user_id = $2
`

type GetFacultyByUserIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetFacultyByUserID(ctx context.Context, arg GetFacultyByUserIDParams) (Faculty, error) {
	row := q.db.QueryRow(ctx, getFacultyByUserID, arg.TenantID, arg.UserID)
	var i Faculty
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DepartmentID,
		&i.EmployeeID,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, tenant_id, user_id, roll_number, program, batch_year, department_id, created_at FROM students WHERE tenant_id = $1 AND id = $2
`

type GetStudentByIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetStudentByID(ctx context.Context, arg GetStudentByIDParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, arg.TenantID, arg.ID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RollNumber,
		&i.Program,
		&i.BatchYear,
		&i.DepartmentID,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByUserID = `-- name: GetStudentByUserID :one
SELECT id, tenant_id, user_id, roll_number, program, batch_year, department_id, created_at FROM students WHERE tenant_id = $1 AND user_id = $2
`

type GetStudentByUserIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetStudentByUserID(ctx context.Context, arg GetStudentByUserIDParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByUserID, arg.TenantID, arg.UserID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RollNumber,
		&i.Program,
		&i.BatchYear,
		&i.DepartmentID,
		&i.CreatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, tenant_id, user_id, roll_number, program, batch_year, department_id, created_at FROM students WHERE tenant_id = $1 ORDER BY roll_number
`

func (q *Queries) ListStudents(ctx context.Context, tenantID uuid.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.RollNumber,
			&i.Program,
			&i.BatchYear,
			&i.DepartmentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
