// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (slug, name, status)
VALUES ($1, $2, 'pending_approval')
RETURNING id, slug, name, custom_domain, status, plan_tier, created_at, updated_at
`

type CreateTenantParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Slug, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CustomDomain,
		&i.Status,
		&i.PlanTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantConfig = `-- name: CreateTenantConfig :one
INSERT INTO tenant_config (tenant_id, grading_system, academic_calendar_type, branding, grading_scale, attendance_threshold_pct)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING tenant_id, grading_system, academic_calendar_type, branding, fee_heads, attendance_threshold_pct, grading_scale, created_at, updated_at
`

type CreateTenantConfigParams struct {
	TenantID               uuid.UUID       `json:"tenant_id"`
	GradingSystem          string          `json:"grading_system"`
	AcademicCalendarType   string          `json:"academic_calendar_type"`
	Branding               json.RawMessage `json:"branding"`
	GradingScale           json.RawMessage `json:"grading_scale"`
	AttendanceThresholdPct pgtype.Numeric  `json:"attendance_threshold_pct"`
}

func (q *Queries) CreateTenantConfig(ctx context.Context, arg CreateTenantConfigParams) (TenantConfig, error) {
	row := q.db.QueryRow(ctx, createTenantConfig,
		arg.TenantID,
		arg.GradingSystem,
		arg.AcademicCalendarType,
		arg.Branding,
		arg.GradingScale,
		arg.AttendanceThresholdPct,
	)
	var i TenantConfig
	err := row.Scan(
		&i.TenantID,
		&i.GradingSystem,
		&i.AcademicCalendarType,
		&i.Branding,
		&i.FeeHeads,
		&i.AttendanceThresholdPct,
		&i.GradingScale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByCustomDomain = `-- name: GetTenantByCustomDomain :one
SELECT id, slug, name, custom_domain, status, plan_tier, created_at, updated_at
FROM tenants
WHERE custom_domain = $1
`

func (q *Queries) GetTenantByCustomDomain(ctx context.Context, customDomain pgtype.Text) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByCustomDomain, customDomain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CustomDomain,
		&i.Status,
		&i.PlanTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, name, custom_domain, status, plan_tier, created_at, updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CustomDomain,
		&i.Status,
		&i.PlanTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, custom_domain, status, plan_tier, created_at, updated_at
FROM tenants
WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CustomDomain,
		&i.Status,
		&i.PlanTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantConfig = `-- name: GetTenantConfig :one
SELECT tenant_id, grading_system, academic_calendar_type, branding, fee_heads, attendance_threshold_pct, grading_scale, created_at, updated_at FROM tenant_config WHERE tenant_id = $1
`

func (q *Queries) GetTenantConfig(ctx context.Context, tenantID uuid.UUID) (TenantConfig, error) {
	row := q.db.QueryRow(ctx, getTenantConfig, tenantID)
	var i TenantConfig
	err := row.Scan(
		&i.TenantID,
		&i.GradingSystem,
		&i.AcademicCalendarType,
		&i.Branding,
		&i.FeeHeads,
		&i.AttendanceThresholdPct,
		&i.GradingScale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTenants = `-- name: ListPendingTenants :many
SELECT id, slug, name, custom_domain, status, plan_tier, created_at, updated_at
FROM tenants
WHERE status = 'pending_approval'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listPendingTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CustomDomain,
			&i.Status,
			&i.PlanTier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, name, custom_domain, status, plan_tier, created_at, updated_at
FROM tenants
ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CustomDomain,
			&i.Status,
			&i.PlanTier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantConfig = `-- name: UpdateTenantConfig :one
UPDATE tenant_config
SET grading_system = COALESCE($2, grading_system),
    academic_calendar_type = COALESCE($3, academic_calendar_type),
    branding = COALESCE($4, branding),
    grading_scale = COALESCE($5, grading_scale),
    attendance_threshold_pct = COALESCE($6, attendance_threshold_pct),
    updated_at = now()
WHERE tenant_id = $1
RETURNING tenant_id, grading_system, academic_calendar_type, branding, fee_heads, attendance_threshold_pct, grading_scale, created_at, updated_at
`

type UpdateTenantConfigParams struct {
	TenantID               uuid.UUID      `json:"tenant_id"`
	GradingSystem          interface{}    `json:"grading_system"`
	AcademicCalendarType   interface{}    `json:"academic_calendar_type"`
	Branding               []byte         `json:"branding"`
	GradingScale           []byte         `json:"grading_scale"`
	AttendanceThresholdPct pgtype.Numeric `json:"attendance_threshold_pct"`
}

func (q *Queries) UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) (TenantConfig, error) {
	row := q.db.QueryRow(ctx, updateTenantConfig,
		arg.TenantID,
		arg.GradingSystem,
		arg.AcademicCalendarType,
		arg.Branding,
		arg.GradingScale,
		arg.AttendanceThresholdPct,
	)
	var i TenantConfig
	err := row.Scan(
		&i.TenantID,
		&i.GradingSystem,
		&i.AcademicCalendarType,
		&i.Branding,
		&i.FeeHeads,
		&i.AttendanceThresholdPct,
		&i.GradingScale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, custom_domain, status, plan_tier, created_at, updated_at
`

type UpdateTenantStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantStatus, arg.ID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CustomDomain,
		&i.Status,
		&i.PlanTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
