// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, role, full_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, email, password_hash, role, full_name, is_active, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	FullName     string    `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, role, full_name, is_active, created_at, updated_at
FROM users
WHERE tenant_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Email    string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, role, full_name, is_active, created_at, updated_at
FROM users
WHERE tenant_id = $1 AND id = $2
`

type GetUserByIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.TenantID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLoginEvent = `-- name: InsertLoginEvent :exec
INSERT INTO login_events (tenant_id, user_id, ip, user_agent)
VALUES ($1, $2, $3, $4)
`

type InsertLoginEventParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Ip        pgtype.Text `json:"ip"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertLoginEvent(ctx context.Context, arg InsertLoginEventParams) error {
	_, err := q.db.Exec(ctx, insertLoginEvent,
		arg.TenantID,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}
